apiVersion: v1
kind: Template
labels:
  demo: coolstore-microservice
  template: coolstore-pipeline
metadata:
  name: coolstore-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${PIPELINE_NAME}
    name: ${PIPELINE_NAME}
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "inventory", "namespace": "${DEV_PROJECT}", "kind": "BuildConfig"},{"name": "inventory", "namespace": "${TEST_PROJECT}", "kind": "DeploymentConfig"},,{"name": "inventory", "namespace": "${PROD_PROJECT}", "kind": "DeploymentConfig"}]'
  spec:
    runPolicy: Serial
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node ('maven') {
            stage 'Build'
            openshiftBuild(buildConfig: 'inventory', namespace: '${DEV_PROJECT}', showBuildLogs: 'true')

            stage 'Promote to TEST'
            openshiftTag(sourceStream: 'inventory', sourceTag: 'latest', namespace: '${DEV_PROJECT}', destinationStream: 'inventory', destinationTag: 'test', destinationNamespace: '${TEST_PROJECT}')

            stage 'Run Tests'
            sleep 10
          }

          stage 'Approve PROD'
          timeout(time:10, unit:'MINUTES') {
            input message:'Approve deployment to Production?'
          }

          node {
            stage 'Promote to PROD'
            openshiftTag(sourceStream: 'inventory', sourceTag: 'test', namespace: '${TEST_PROJECT}', destinationStream: 'inventory', destinationTag: 'prod', destinationNamespace: '${PROD_PROJECT}')

            stage 'Smoke Tests PROD'
            sleep 10
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
parameters:
- description: The name for the pipeline.
  displayName: Pipeline Name
  name: PIPELINE_NAME
  required: true
  value: coolstore-pipeline
- description: DEV project name containting the buildconfigs
  displayName: DEV Project Name
  name: DEV_PROJECT
  required: true
- description: TEST project name containting the buildconfigs
  displayName: TEST Project Name
  name: TEST_PROJECT
  required: true
- description: PROD project name containting the buildconfigs
  displayName: PROD Project Name
  name: PROD_PROJECT
  required: true
- description: GitHub webhook secret
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: Generic webhook secret
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
